# Generated by Django 5.2.6 on 2025-11-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hệ Thống Kệ Xoay', max_length=100)),
                ('current_shelf_at_gate', models.CharField(default='A', max_length=1)),
                ('target_shelf', models.CharField(blank=True, max_length=1, null=True)),
                ('is_moving', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='carousel.carousel')),
            ],
            options={
                'verbose_name_plural': 'Shelves',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trays', to='carousel.shelf')),
            ],
            options={
                'ordering': ['shelf__name', 'level'],
                'unique_together': {('shelf', 'level')},
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số Lượng')),
                ('capacity', models.PositiveIntegerField(default=51, verbose_name='Sức Chứa Max')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_locations', to='products.productbatch', verbose_name='Lô Hàng')),
                ('capacity_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations_cap', to='products.unitofmeasure', verbose_name='Đơn Vị (Max)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='products.product', verbose_name='Sản Phẩm')),
                ('quantity_uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations_qty', to='products.unitofmeasure', verbose_name='Đơn Vị (SL)')),
                ('tray', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='carousel.tray')),
            ],
            options={
                'verbose_name': 'Vị Trí Kho',
                'verbose_name_plural': 'Vị Trí Kho',
            },
        ),
    ]
