# Generated by Django 5.2.6 on 2025-10-14 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ/Quê quán')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='patient_avatars/', verbose_name='Ảnh đại diện')),
                ('citizen_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số CCCD')),
                ('health_insurance_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số BHYT')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dân tộc')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Chưa rõ')], default='Unknown', max_length=10, verbose_name='Nhóm máu')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Tiền sử dị ứng')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Bệnh sử (bệnh mãn tính)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, unique=True, verbose_name='Mã thuốc')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Tên thuốc')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Số lượng')),
                ('unit', models.CharField(choices=[('Viên', 'Viên'), ('Hộp', 'Hộp'), ('Chai', 'Chai'), ('Ống', 'Ống'), ('Gói', 'Gói')], max_length=20, null=True, verbose_name='Đơn vị')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Giá nhập')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Giá bán')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Chờ lấy thuốc'), ('Dispensed', 'Đã lấy thuốc'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn tất')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient', verbose_name='Full Name ')),
            ],
            options={
                'verbose_name_plural': 'Prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(null=True, verbose_name='Quantity')),
                ('is_collected', models.BooleanField(default=False, verbose_name='Đã lấy thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dashboard.prescription', verbose_name='Toa thuốc')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Prescription Details',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.prescription', verbose_name='Từ toa thuốc')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm sản phẩm')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard.productcategory', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productcategory', verbose_name='Nhóm sản phẩm'),
        ),
    ]
