# Generated by Django 5.2.6 on 2025-10-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit Name')),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AlterField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.prescription', verbose_name='From Prescription'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='patient_avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Chưa rõ')], default='Unknown', max_length=10, verbose_name='Blood Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='citizen_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Citizen ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_insurance_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Health Insurance ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Medical History'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ lấy thuốc'), ('Dispensed', 'Đã lấy thuốc'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='is_collected',
            field=models.BooleanField(default=False, verbose_name='Collected'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='dashboard.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.productcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='import_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Import Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dashboard.productcategory', verbose_name='Parent Category'),
        ),
        migrations.AddField(
            model_name='prescriptiondetail',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.unitofmeasure', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.unitofmeasure', verbose_name='Base Unit of Measure'),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.FloatField(verbose_name='Conversion Factor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='dashboard.product', verbose_name='Product')),
                ('uom_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_from', to='dashboard.unitofmeasure', verbose_name='From Unit')),
                ('uom_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_to', to='dashboard.unitofmeasure', verbose_name='To Unit (Base)')),
            ],
            options={
                'verbose_name_plural': 'Bills of Materials',
                'unique_together': {('product', 'uom_from')},
            },
        ),
    ]
