# Generated by Django 5.2.6 on 2025-10-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_product_description_productcategory_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uom',
            new_name='base_uom',
        ),
        migrations.AddField(
            model_name='product',
            name='uom_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.uomcategory', verbose_name='UoM Category'),
        ),
    ]
