# Generated by Django 5.2.6 on 2025-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_unitofmeasure_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='conversion_factor',
            field=models.IntegerField(verbose_name='Conversion Factor'),
        ),
    ]
