# Generated by Django 5.2.6 on 2025-10-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='unique_code',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
