# Generated by Django 5.2.6 on 2025-10-26 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_prescription_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
