# Generated by Django 5.2.6 on 2025-11-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Gender')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='patient_avatars/', verbose_name='Avatar')),
                ('citizen_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Citizen ID')),
                ('health_insurance_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Health Insurance ID')),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ethnicity')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Chưa rõ')], default='Unknown', max_length=10, verbose_name='Blood Type')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='Medical History')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'dashboard_patient',
                'ordering': ['-created_at'],
            },
        ),
    ]
