# Generated by Django 5.2.6 on 2025-11-23 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True, unique=True, verbose_name='Product Code')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Product Name')),
                ('import_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Import Price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Sale Price')),
                ('reorder_point', models.PositiveIntegerField(default=10, verbose_name='Reorder Point')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Default Supplier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'dashboard_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Unit of Measure')),
                ('uom_type', models.CharField(choices=[('reference', 'Reference Unit for this category'), ('bigger', 'Bigger than the reference Unit of Measure'), ('smaller', 'Smaller than the reference Unit of Measure')], max_length=20, verbose_name='Type')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('rounding_precision', models.FloatField(default=0.01, verbose_name='Rounding Precision')),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
                'db_table': 'dashboard_unitofmeasure',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'UoM Categories',
                'db_table': 'dashboard_uomcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Mã Lô')),
                ('expiry_date', models.DateField(verbose_name='Hạn Sử Dụng')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số Lượng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Sản Phẩm')),
            ],
            options={
                'db_table': 'products_batch',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'db_table': 'dashboard_productcategory',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unitofmeasure', verbose_name='Base Unit of Measure'),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='products.uomcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.uomcategory', verbose_name='UoM Category'),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.IntegerField(verbose_name='Conversion Factor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product', verbose_name='Product')),
                ('uom_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_from', to='products.unitofmeasure', verbose_name='From Unit')),
                ('uom_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_to', to='products.unitofmeasure', verbose_name='To Unit')),
            ],
            options={
                'verbose_name_plural': 'Bills of Materials',
                'db_table': 'dashboard_billofmaterials',
                'unique_together': {('product', 'uom_from', 'uom_to')},
            },
        ),
    ]
